/**
 * lib/export-review.ts — Export ReviewReport as Markdown, JSON, or clipboard
 */

import type { ReviewReport, ReviewSection, ReviewIssue } from "./review-engine";

// ---------------------------------------------------------------------------
// Markdown Export
// ---------------------------------------------------------------------------

function renderIssueMarkdown(issue: ReviewIssue): string {
  const sevBadge = `[${issue.severity} ${issue.dimension.toUpperCase()}]`;
  const lines = [
    `### Issue ${issue.number}: ${issue.description} ${sevBadge}`,
    `**File**: \`${issue.file}\`${issue.line ? `:${issue.line}` : ""}`,
    "",
    `**Recommended**: ${issue.recommendation.label} (human: ${issue.recommendation.effort.human} / CC: ${issue.recommendation.effort.cc}, completeness: ${issue.recommendation.completeness}/10)`,
  ];

  for (let i = 0; i < issue.alternatives.length; i++) {
    const alt = issue.alternatives[i]!;
    const letter = String.fromCharCode(65 + i); // A, B, C
    lines.push(
      `**Alternative ${letter}**: ${alt.label} (human: ${alt.effort.human} / CC: ${alt.effort.cc}, completeness: ${alt.completeness}/10)`
    );
  }

  return lines.join("\n");
}

function renderSectionMarkdown(section: ReviewSection): string {
  if (section.issues.length === 0) {
    return `## ${section.name} (Score: ${section.score}/10)\n\nNo issues found. Section passes review.\n`;
  }

  const header = `## ${section.name} (Score: ${section.score}/10) — ${section.issues.length} issue${section.issues.length > 1 ? "s" : ""}\n`;
  const issues = section.issues.map(renderIssueMarkdown).join("\n\n");
  return `${header}\n${issues}\n`;
}

export function exportMarkdown(report: ReviewReport): string {
  const readinessPct = Math.round(report.readiness * 100);
  const lines = [
    `# VibeCheck Review Report — ${report.project}`,
    "",
    `## Scan Summary`,
    `- **Files scanned**: ${report.filesScanned} | **Defects**: ${report.totalDefects} | **Readiness**: ${readinessPct}%`,
    `- **Scanned at**: ${new Date(report.scannedAt).toLocaleString()}`,
    "",
    renderSectionMarkdown(report.engineering),
    renderSectionMarkdown(report.design),
    renderSectionMarkdown(report.qa),
    `## Decision Summary`,
    "",
    "| # | Issue | Dimension | Recommended | Score |",
    "|---|-------|-----------|-------------|-------|",
  ];

  const allIssues = [
    ...report.engineering.issues,
    ...report.design.issues,
    ...report.qa.issues,
  ].sort((a, b) => {
    const order = { P0: 0, P1: 1, P2: 2, P3: 3 };
    return order[a.severity] - order[b.severity];
  });

  for (const issue of allIssues.slice(0, 15)) {
    lines.push(
      `| ${issue.number} | ${issue.description.slice(0, 50)} | ${issue.dimension} | ${issue.recommendation.label.slice(0, 40)} | ${issue.recommendation.completeness}/10 |`
    );
  }

  if (allIssues.length > 15) {
    lines.push("");
    lines.push(`*${allIssues.length - 15} additional issues not shown. Export JSON for the full list.*`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [VibeCheck](https://vibecheck.dev) — Antifragile Production Hardening*");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// JSON Export
// ---------------------------------------------------------------------------

export function exportJSON(report: ReviewReport): string {
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Clipboard (compact summary)
// ---------------------------------------------------------------------------

export function exportClipboard(report: ReviewReport): string {
  const readinessPct = Math.round(report.readiness * 100);
  const lines = [
    `VibeCheck Review: ${report.project}`,
    `Readiness: ${readinessPct}% | ${report.totalDefects} defects across ${report.filesScanned} files`,
    "",
    `Engineering: ${report.engineering.score}/10 (${report.engineering.issues.length} issues)`,
    `Design: ${report.design.score}/10 (${report.design.issues.length} issues)`,
    `QA: ${report.qa.score}/10 (${report.qa.issues.length} issues)`,
    "",
    "Top actions:",
  ];

  for (const action of report.topActions) {
    lines.push(`  ${action.number}. [${action.severity}] ${action.description} → ${action.recommendation.label}`);
  }

  return lines.join("\n");
}
